/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarySystem;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author SHERMAN
 */
public class CreateAccount extends javax.swing.JFrame {
Connection con=connect.connectdb();
        PreparedStatement pst ;
        ResultSet rs;
    /**
     * Creates new form CreateAccount
     */
    public CreateAccount() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(CreateAccount.EXIT_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        answear = new javax.swing.JTextField();
        cell = new javax.swing.JTextField();
        retype = new javax.swing.JPasswordField();
        pass = new javax.swing.JPasswordField();
        signinb = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        sec = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));

        answear.setBackground(new java.awt.Color(51, 0, 51));
        answear.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        answear.setForeground(new java.awt.Color(255, 255, 255));
        answear.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        answear.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ANSWEAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 1, 10), new java.awt.Color(255, 255, 255))); // NOI18N
        answear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answearActionPerformed(evt);
            }
        });

        cell.setBackground(new java.awt.Color(51, 0, 51));
        cell.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        cell.setForeground(new java.awt.Color(255, 255, 255));
        cell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PHONE NUMBER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        cell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellActionPerformed(evt);
            }
        });
        cell.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cellKeyPressed(evt);
            }
        });

        retype.setBackground(new java.awt.Color(51, 0, 51));
        retype.setForeground(new java.awt.Color(255, 255, 255));
        retype.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        retype.setText("jPasswordField1");
        retype.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RE-TYPE PASSWORD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 1, 10), new java.awt.Color(255, 255, 255))); // NOI18N
        retype.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                retypeFocusGained(evt);
            }
        });
        retype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retypeActionPerformed(evt);
            }
        });

        pass.setBackground(new java.awt.Color(51, 0, 51));
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass.setText("jPasswordField1");
        pass.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PASSWORD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 1, 10), new java.awt.Color(255, 255, 255))); // NOI18N
        pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFocusGained(evt);
            }
        });

        signinb.setBackground(new java.awt.Color(51, 0, 51));
        signinb.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 11)); // NOI18N
        signinb.setForeground(new java.awt.Color(255, 255, 255));
        signinb.setText("CREATE");
        signinb.setBorder(null);
        signinb.setBorderPainted(false);
        signinb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CREATE AN ACCOUNT");

        email.setBackground(new java.awt.Color(51, 0, 51));
        email.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EMAIL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        sec.setBackground(new java.awt.Color(51, 0, 51));
        sec.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        sec.setForeground(new java.awt.Color(255, 255, 255));
        sec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "what is your favourate singer", "what is your fathers name", "what is your mothers name", "what is your pets name", " " }));
        sec.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SECURITY QUESTION");

        name.setBackground(new java.awt.Color(51, 0, 51));
        name.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NAME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
        });
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameMouseClicked(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(148, 148, 148))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(signinb, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(answear)
                                .addComponent(cell)
                                .addComponent(retype)
                                .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                .addComponent(email)
                                .addComponent(name))
                            .addComponent(jLabel4))))
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cell, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(9, 9, 9)
                .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answear, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(retype, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signinb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 400, 630));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/screen-1-128x128.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 130, 130));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("already have an account?  ");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cellActionPerformed
    public boolean checkemail(String email){
        String check="^[\\w!#$%&'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&'*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}";
        Pattern pattern=Pattern.compile(check);
        Matcher match=pattern.matcher(email);
        return match.matches();
        
    }
    //if( pass.getText().equals(retype.getText())
    public void checkpass(){
        
       
    }
    private void signinbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbActionPerformed
   if(("".equals(email.getText())) || ("".equals(name.getText()) )  || ("".equals(cell.getText())) || ("".equals(answear.getText()))    || ("".equals(pass.getText()))                            ){
       JOptionPane.showMessageDialog(null, "please fill in all the blanks");
      
   }
   else{
      if(checkemail(email.getText())==false){
           JOptionPane.showMessageDialog(null, "please enter a valid email");
           
    }
      else{
          if((pass.getText().equals(retype.getText()))){
           try {
       
        // TODO add your handling code here:
        String sql="insert into user (email,name,cellno,securtyq,password,answear) values(?,?,?,?,?,?)";
       //  ('"+email.getText()+"','"+name.getText()+"','"+cell.getText()+"','"+answear.getText()+"','"+pass.getText()+"')
    pst=con.prepareStatement(sql);
    pst.setString(1,email.getText());
    pst.setString(2,name.getText());
    pst.setString(3,cell.getText());
    pst.setString(4,(String)sec.getSelectedItem());
    pst.setString(5,pass.getText());
    pst.setString(6,answear.getText());
       
   
      
        pst.execute();
      
        
        
            JOptionPane.showMessageDialog(null, "ACCOUNT CREATED");
            LOGIN i=new LOGIN();
            this.hide();
            i.setVisible(true);
          //  pst.close();
          //  rs.close();
            
            
            //accountnumber();
            // adduser();
            // System.out.println(who());
            
        
        
    } catch (SQLException ex) {
        Logger.getLogger(CreateAccount.class.getName()).log(Level.SEVERE, null, ex);
            

        //accountnumber();
        // adduser();
        // System.out.println(who());
    } 
        }
           else{
            JOptionPane.showMessageDialog(null, "passwords do not match");
        }
         
        }}
    }//GEN-LAST:event_signinbActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         this.hide();
        LOGIN create =new  LOGIN();
        create.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void retypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retypeActionPerformed

    private void answearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answearActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusGained
        // TODO add your handling code here:
        pass.setText(null);
    }//GEN-LAST:event_passFocusGained

    private void retypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_retypeFocusGained
        // TODO add your handling code here:
        retype.setText(null);
    }//GEN-LAST:event_retypeFocusGained

    private void cellKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cellKeyPressed
        // TODO add your handling code here:
        int leng;
        String phoneno=cell.getText();
        leng=phoneno.length();
        
        char c=evt.getKeyChar();
        
        if(Character.isLetter(c)){
            cell.setEditable(false);
        }
        else{
                 cell.setEditable(true);
                 if(evt.getKeyChar()>'0'&&evt.getKeyChar()<='9'){
                    if(leng<10){
                        cell.setEditable(true);
                    } 
                    else{
                        cell.setEditable(false);
                    }
                 }
                 
                 
                }
    
    }//GEN-LAST:event_cellKeyPressed

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isDigit(c)){
            name.setEditable(false);
            name.setText("please enter a valid name");
            name.getCaret().setVisible(false);
        }
        else{
              
            name.setEditable(true);
                }
    }//GEN-LAST:event_nameKeyPressed

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        // TODO add your handling code here:
         
    }//GEN-LAST:event_nameFocusGained

    private void nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseClicked
        // TODO add your handling code here:
        name.getCaret().setVisible(true);
        name.setText(null);
    }//GEN-LAST:event_nameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answear;
    private javax.swing.JTextField cell;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField retype;
    private javax.swing.JComboBox sec;
    private javax.swing.JButton signinb;
    // End of variables declaration//GEN-END:variables
}
